# Generated by Django 4.2.10 on 2025-12-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_same_as_shipping',
            field=models.BooleanField(default=True),
        ),
    ]
